version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    groups:
      npm-testing:
        dependency-type: "development"
        patterns:
          - "@playwright/test"
          - "@testing-library/*"
          - "@vitest/*"
          - "vitest*"
          - "msw"
          - "jsdom"
      npm-production:
        dependency-type: "production"
        patterns:
          - "*"
      npm-dev-tooling:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
